name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js and cache dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: kanban-board/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('kanban-board/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install dependencies
      - run: yarn install --frozen-lockfile
        working-directory: kanban-board

      # Set SHA for affected commands
      - uses: nrwl/nx-set-shas@v4
        with:
          working-directory: kanban-board

      # Run Nx affected commands for lint, test, build, and e2e
      - run: yarn nx affected --target=lint --base=master --head=$(git rev-parse HEAD)
        working-directory: kanban-board
      - run: yarn nx affected --target=test --base=master --head=$(git rev-parse HEAD)
        working-directory: kanban-board
      - run: yarn nx affected --target=build --base=master --head=$(git rev-parse HEAD)
        working-directory: kanban-board
      - run: yarn nx affected --target=e2e --base=master --head=$(git rev-parse HEAD)
        working-directory: kanban-board
